### ISSUE TITLE
Add picture

### ISSUE THREAD

**Issue by AyoPrez** [samuelmeuli/mini-diary#1]
I think it would be nice to have the possibility to add an image to everyday diary page.

**Comment by samuelmeuli** [comment]
Hi @AyoPrez,

Thanks for your interest in the app!

That feature was intentionally left out to keep the app as clean and simple as possible. Mini Diary is not meant to have a lot of features, but provide a distraction-less writing experience. Also, introducing this now would require significant changes to how the data is stored. So I'm afraid this is not going to be implemented.
