### ISSUE TITLE
Tags, geotags, statistics

### ISSUE THREAD

**Issue by github2099** [samuelmeuli/mini-diary#14]
How about adding: 
tags, geotags, and statistics of diary entries?

**Comment by samuelmeuli** [comment]
Regarding tags and geotags: Its simplicity and intuitive design are what make Mini Diary different from other apps. I'm afraid adding too many features would move it away from that philosophy. There are many other great diary apps if you need a tool with more advanced features :)

Stats are a cool idea, do you have any specific ones in mind?

**Comment by github2099** [comment]
like number of entries created, average words, etc

**Comment by Quilljou** [comment]
Can it support drag the window

**Comment by samuelmeuli** [comment]
That's supported. You can drag the top of the window.

**Comment by druc** [comment]
A word counter would be great!

I would also like to be able to shorten the width (or to decide a standard width) of the content area - it looks bad on a large screen.

I know I could just resize the window until I reach the width I like, but I'd love to be able to enter fullscreen/focus mode and having it look great.

I never worked with electron, but I can work out a PR if you're willing to allow any of these ideas.

Thanks for the awesome work!

**Comment by samuelmeuli** [comment]
I've split this issue up into #25 and #26.
