### ISSUE TITLE
Add future events

### ISSUE THREAD

**Issue by massinlaaouaj** [samuelmeuli/mini-diary#16]
First thanks for building this beatiful and intuitive application, I use frequenly to post my notes, but I wish write some future events in the diary and I can't, do you plan to implement??

**Comment by samuelmeuli** [comment]
Thanks for the feedback. That's an intentional limitation (which I think helps with navigation in the calendar), as I didn't expect people to write diary entries for days in the future 😉

May I ask for your use case for this feature? I can think about adding an option to enable this.

**Comment by github2099** [comment]
> 
> 
> First thanks for building this beatiful and intuitive application, I use frequenly to post my notes, but I wish write some future events in the diary and I can't, do you plan to implement??

You can manually change date in OS to write for days in future.

**Comment by massinlaaouaj** [comment]
@samuelmeuli Yeah enable the option Samuel, cause for now I only can write the notes for today, but if you enable this option, I can open de Diary and see what I note yesterday or other day for the this day.

@github2099 It's an option, but when I go to job, in there computers I can't change the data in OS.
