### ISSUE TITLE
Unable to search special characters

### ISSUE THREAD

**Issue by github2099** [samuelmeuli/mini-diary#18]
Special characters, like @ # etc can never be searched. I wanted to add hashtags. Instead of something like **#sample**, I had to type **sample** in search, which confused with any entry with the same word in content.

**Comment by samuelmeuli** [comment]
@github2099 I've now customized the tokenizer of the full-text search library to allow this. Let me know if you think it makes sense to exclude other characters.

**Comment by github2099** [comment]
Is it made available with the latest release 2.3.0?

**Comment by samuelmeuli** [comment]
No, it will be in the next version.
