### ISSUE TITLE
Spellcheck

### ISSUE THREAD

**Issue by connorhatch** [samuelmeuli/mini-diary#2]
Any plans to implement spellcheck?

**Comment by samuelmeuli** [comment]
That's a good idea. I'll look into this.

**Comment by samuelmeuli** [comment]
It looks like there isn't a straightforward way to implement spell checking in Electron apps right now. There's [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) which unfortunately has lots of issues (broken language auto-detection, performance problems, and no clear way to turn it off) and seems to be unmaintained. Unfortunately, I couldn't find any better alternatives.

It probably makes sense to wait with this feature and keep an eye on https://github.com/electron/electron/issues/3211.

**Comment by github2099** [comment]
Any news?

**Comment by samuelmeuli** [comment]
I've had another look at integrating [electron-spellchecker](https://github.com/electron-userland/electron-spellchecker) into Mini Diary. There have been improvements, but I'm still not happy with its performance, language detection is broken, and including the library would increase the app size by 25 MB (!). The package also doesn't seem to be very actively maintained. Therefore, I'd rather not merge this into `master`.

If this feature is very important to someone, you could build the app yourself from the [spell-checking branch](https://github.com/samuelmeuli/mini-diary/tree/spell-checking) branch.

And if anyone knows a better solution, I'd be happy to hear it! I'm also still hoping for built-in support for spell checking in Electron :)

**Comment by samuelmeuli** [comment]
Good news: https://github.com/electron/electron/releases/tag/v8.0.0-beta.2

I'll look into this once the app is updated for Electron 8.

**Comment by samuelmeuli** [comment]
Native spellchecking will be available in the next release :)

**Comment by HeyVern** [comment]
I see that you added it in preferences....but how does one actually use Spell Check?  Did it ever actually make it to the release?
