### ISSUE TITLE
New appimage does not work on Manjaro Gnome

### ISSUE THREAD

**Issue by tiotrom** [samuelmeuli/mini-diary#21]
I am using appimagelauncher but it does nothing. Usually I can run or integrate and run. This time none works. How to debug? Cheers!

**Comment by samuelmeuli** [comment]
Hi, thanks for reporting this. I've just tested the AppImage on Ubuntu and it's working for that platform.

Did the installation with AppImageLauncher work for previous versions of the app?

If you have Node installed, would you mind testing whether you can [run the app locally](https://github.com/samuelmeuli/mini-diary#development)? If not, I can spin up a VM and have a look as well.

**Comment by tiotrom** [comment]
https://github.com/samuelmeuli/mini-diary/releases/download/v2.0.1/mini-diary-2.0.1-x86_64.AppImage Works just fine. I may try to run the app locally like you suggested but at the moment I can't so if you are able to test on a Manjaro install that would be helpful :). I've also deleted the old config for the app to make sure the config didn't interfere with the new appimage. But made no difference.

**Comment by samuelmeuli** [comment]
This problem seems to be related to sandboxing in Electron v5 (see https://github.com/electron-userland/electron-builder/issues/3872). I'm downgrading to v4 again for now to fix this.
