### ISSUE TITLE
Installer warned by Windows Defender smartscreen

### ISSUE THREAD

**Issue by github2099** [samuelmeuli/mini-diary#23]
![mini_diary_setup_2 2 0_exe](https://user-images.githubusercontent.com/49584984/58734304-fab01200-83ab-11e9-8f3a-c8f056e00b05.png)

**Comment by samuelmeuli** [comment]
This warning appears because the Windows app isn't signed. Since I'm not making any money from the app, buying a code signing certificate isn't worth it for me.
