### ISSUE TITLE
Encrypt / decrypt command line

### ISSUE THREAD

**Issue by 7aklhz** [samuelmeuli/mini-diary#24]
Hi

I would like to decrypt and encrypt the .txt file using (Mac) command line. Can this be done? What encryption type are you using? I've tried openssl but i get "bad magic number" after inserting my password. 

Thank you

Konrad

**Comment by samuelmeuli** [comment]
Hi @KonradHolubek,

That should be possible. Electron 4+ uses BoringSSL. You'll first need to [hash your password](https://github.com/samuelmeuli/mini-diary/blob/47405451d357f6a588dad2ab84dc50aaa8bc9808/src/renderer/files/diary/hashPassword.ts#L9-L16) and use that string to [decrypt your diary file](https://github.com/samuelmeuli/mini-diary/blob/47405451d357f6a588dad2ab84dc50aaa8bc9808/src/renderer/files/fileAccess.ts#L27-L32).

**Comment by 7aklhz** [comment]
Thank you. If any one is wondering how to do this, i created a script, named decrypt.sh, that I run by typing 
`node decrypt.sh <password>`

The script is : 
`
#!/bin/bash
#HOW TO : To use this script type node decrypt.sh <password>
const args = process.argv.slice(2)
#console.log("the password is "+args[0])
const crypto = require('crypto');
const fs = require('fs');
const password = args[0];
const CIPHER = "sha512";
const CIPHERFile = "aes-192-cbc";
const ITERATIONS = 500000;
const KEY_BYTE_LENGTH = 64;
const SALT =
"KvAUQORXF8OBYXcYmIwHBpahc7I9Td+qe+H1/eGTaXvI9XfRLngERiC4ufpfx4mqvQgITb0t+ns840lJcRRTKQmF65vje5/Wfb99Nsu6kxDudTiM5pKUcmn36fEJ9/lhFIyBd18Unouh3OiTxO+5xhGugtujNARLijOzkDkYy/8=";
filePath ="mini-diary.txt";
const hash = crypto.pbkdf2Sync(password, SALT, ITERATIONS, KEY_BYTE_LENGTH, CIPHER);
console.log ("the hash password is: "+hash.toString("hex"));
var hashedPassword = hash.toString("hex");
const data = fs.readFileSync(filePath);
const decipher = crypto.createDecipher(CIPHERFile, hashedPassword);
const fileContent = Buffer.concat([decipher.update(data), decipher.final()]);
console.log("the content is :"+fileContent.toString());`
