### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ldbl1** [samuelmeuli/mini-diary#3]
Are you planning to have translations in your app? I could help you with Spanish.

**Comment by samuelmeuli** [comment]
Hey, thanks for the offer! Adding translations is a good idea, I'll think about what's the best way to implement this.

**Comment by sergiopjf** [comment]
I can also help you with Brazilian Portuguese.

**Comment by samuelmeuli** [comment]
I've now implemented a way to localize the app and added [instructions](https://github.com/samuelmeuli/mini-diary#localization) to the README.

@ldbl1 @sergiopjf If you guys would be willing to help out, that would be great! :)

I'm leaving this issue open in case anybody else is willing to contribute translations for other languages.
