### ISSUE TITLE
Support checkbox and nested lists.

### ISSUE THREAD

**Issue by benstigsen** [samuelmeuli/mini-diary#31]
- [x] I think a checkbox for personal goals would be really nice, especially since there's the "Allow entries in the future" option.

And indented / nested lists. So currently you can only do:

- Item 1
- Item 2

Where I'd like to be able to do:  
- Item 1
    - Item 1.1
- Item 2

**Comment by samuelmeuli** [comment]
Hi @BenTearzz, thanks for the feedback!

Totally agree regarding nested lists. I'm already working on supporting this :)

Currently, I'd rather not add support for checkboxes, though. I'd like to keep the editor UI as simple as possible and therefore avoid adding any new buttons.

**Comment by benstigsen** [comment]
Actually yeah, I've thought more about it and a checkbox wouldn't fit in a diary, it's much better suited for a to-do list. Whereas the diary would be better for stating current progress on those goals and if they've been completed... so in other words, understandable! :D
