### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by dmcfaddengalway** [samuelmeuli/mini-diary#34]
Any plans to implement a word count option? I'd be interested in this feature and seeing what is required for this work.

**Comment by dmcfaddengalway** [comment]
Sorry to clarify, this is below the individual entry, not in the statistics modal box that oges over all entries.

**Comment by samuelmeuli** [comment]
I like the idea. Having a word count in the editor would be nice, we just need to make sure it fits in well in the UI and isn't too obtrusive.

**Comment by dmcfaddengalway** [comment]
@samuelmeuli great! Do you use Sketch or Figma for managing the design? If not, I can make a quick draft of the UI in Figma and add in how I see word count fitting it to this. Let me know is that interests you.

**Comment by samuelmeuli** [comment]
I used to have a UI mockup in Illustrator, but it's out of date. If you'd like to create one (with whatever tool you like), that would be great. We can also just iterate on a PR as this should be a pretty small change. Whatever works best for you.

I probably won't be able to look into this closely in the next few weeks though, but I'm hoping to dedicate some time to the app after that :)

**Comment by alexriabtsev** [comment]
yeah! that's exactly what lacks in the Mini Diary for my morning pages :)

@samuelmeuli I'm looking forward to seeing this feature!

**Comment by samuelmeuli** [comment]
Implemented as part of a toolbar redesign:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/22477950/74003334-ccf08380-49a4-11ea-8983-94668f4b8273.png">

The styling might not be ideal yet (e.g. the toolbar contrast). I'd be happy to hear your thoughts :)

**Comment by alexriabtsev** [comment]
Cool! But I can't see it in 2.5.6?

**Comment by samuelmeuli** [comment]
It's gonna be in the next release
