### ISSUE TITLE
Auto lock when idle

### ISSUE THREAD

**Issue by samrahman** [samuelmeuli/mini-diary#35]
I was checking Electron examples, thus got to know mini-diary. Great work!

This is a feature request, can be handy. After few idle minutes, the diary will be locked automatically. User should be able to configure this settings i.e minutes. This is exclusive than the OS idle time.

Thanks

**Comment by samuelmeuli** [comment]
Thanks!

The app already locks automatically when the operating system's screen lock is activated (see [`powerMonitor`](https://electronjs.org/docs/api/power-monitor)). What would be the benefit of additionally introducing this feature on the app level? If users want more security, wouldn't they just change the OS's auto lock time?

**Comment by dmcfaddengalway** [comment]
I see the reason for not introducing this, however I set mine to quite long as my laptop stays in my room most of the time, but for certain apps (especially ones with high security background) I like to have more control over it. 

EDIT: Also I think this would be good incase you switch away from the app to go to another, then leave your computer and someone swipes. Keeping it more secure from unintended views.

I like this idea. Benefit would be the user feels more in control.

**Comment by samrahman** [comment]
As Daniel said, users are more likely going to use the diary from their personal laptop, often they don't mind leave the computer open for longer but there's a possibility of unintended views.

**Comment by samuelmeuli** [comment]
I've given this some more thought and decided I'd rather not add the feature.

Generally, I'd like to avoid introducing new settings whenever possible.

Furthermore, auto-locking is already handled by the OS, and I think that's enough. If users want more security, they can change the global setting. The diary probably isn't the only sensitive piece of information on the machine anyway :)
