### ISSUE TITLE
Export is failling on mac os.

### ISSUE THREAD

**Issue by albertwh1te** [samuelmeuli/mini-diary#38]
## OS
Mac Os 10.15.1 (19B88)
## What I have done
I download this software from appstore. I write my first diary. I click the file >> export >> export to json
And this error message shows.
## Error Message 
Unhandled Error
TypeError: Cannot read property 'webContents' of null
    at M (/Applications/Mini Diary.app/Contents/Resources/app.asar/bundle/main.js:8:310433)
    at click (/Applications/Mini Diary.app/Contents/Resources/app.asar/bundle/main.js:8:312376)

**Comment by samuelmeuli** [comment]
Hi @MarkWh1te, thanks for the detailed report!

Unfortunately, [Apple no longer accepts Electron apps on the App Store](https://9to5mac.com/2019/11/04/electron-app-rejections), so I won't be able to fix that version.

Is this also happening with the [non-App-Store version](https://github.com/samuelmeuli/mini-diary/releases/download/v2.4.3/Mini-Diary-2.4.3.dmg)? I just tested it and it's working for me.

**Comment by albertwh1te** [comment]
Thanks for your reply, my dear friend. I have a little suggestion that it would be wonderful if note this issue in README or website. 
Thank you again for your amazing work. This application is perfect.
