### ISSUE TITLE
Can't save diary in another drive

### ISSUE THREAD

**Issue by Son-Guhun** [samuelmeuli/mini-diary#43]
![image](https://user-images.githubusercontent.com/22954418/69899053-d1af1080-133f-11ea-80ef-ba85fb6d2532.png)

As can be seen from the image above, you can't move your diary to another drive. Possibly because the file is just being renamed? The file would need to actually be copied to the new drive and then deleted.

**Comment by samuelmeuli** [comment]
Thanks for reporting! This should be fixed in the next release.

**Comment by Son-Guhun** [comment]
Nice, that was fast! Thank you.
