### ISSUE TITLE
Auto-update fails with error

### ISSUE THREAD

**Issue by fonger900** [samuelmeuli/mini-diary#48]
**Stack trace:**

```
Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

---

**Environment:**

```
Mini Diary 2.5.1
Electron 7.1.3
darwin 19.2.0
Locale: en-US
```

---

**Error description:**

**Comment by samuelmeuli** [comment]
@fonger900 Could you please provide an error description so I can try to reproduce the error?

**Comment by samuelmeuli** [comment]
It's a bug in `electron-updater`, which is no longer compatible with Electron v7.1.3+: https://github.com/electron-userland/electron-builder/issues/4543. Looks like I lost all users who updated the app to v2.5.2 because the bug breaks auto-updating…

If you're affected, please reinstall the app.
