### ISSUE TITLE
Option to override first day of the week

### ISSUE THREAD

**Issue by github2099** [samuelmeuli/mini-diary#56]
Is it usually Sunday, can we change to Monday

**Comment by samuelmeuli** [comment]
Your calendar's first day of the week is determined by your system locale. For example, it's Sunday for `en-US` and Monday for `en-UK`.

**Comment by github2099** [comment]
What if its en-US but want to have Monday as first day...?

**Comment by samuelmeuli** [comment]
This behavior is delegated to [Moment.js](https://momentjs.com) and [react-day-picker](https://react-day-picker.js.org). There's currently no option for overriding the default. I'm open for pull requests, though :)

The relevant calendar prop is specified here: https://github.com/samuelmeuli/mini-diary/blob/ed29aa9c0c2b902240824a6746c09f87ed6a1588/src/renderer/components/elements/Calendar/CalendarView/Calendar.tsx#L57

**Comment by samuelmeuli** [comment]
An option will be available in the next release.
