### ISSUE TITLE
Go-to specific date

### ISSUE THREAD

**Issue by mjoez** [samuelmeuli/mini-diary#57]
If I want to add an entry on a past date it is high effort to navigate to this date.
It would be greate to have "date selection" possibility.

**Comment by samuelmeuli** [comment]
Agreed, this should be added.

For now, you can use shortcuts (⌘ + left/right arrow) if you want to navigate between months more quickly.

**Comment by samuelmeuli** [comment]
This feature will be added in the next release.

**Comment by mjoez** [comment]
Hi Samuel, great to hear that, thanks!
