### ISSUE TITLE
Template support

### ISSUE THREAD

**Issue by DrLeucine** [samuelmeuli/mini-diary#59]
Hi!

I'm really enjoying Mini Diary, the design is perfect. Usually when I write an entry, I tend to answer specific questions, eg. "What did you learn?" or "What decisions did you make?" 

I think it could be useful, if the user was able to specify a template for an entry. It could be stored in GitHub Gists or simply as an .md file:

```
# Example of a template

## What did you learn?

## What decisions did you make?

[...]
```

Let me know your thoughts.

**Comment by samuelmeuli** [comment]
Hi @universvm,

Thanks for sharing the feature idea! I like it, this would definitely be a useful feature.

One problem is that I'd really like to avoid users having to deal with Gists or Markdown/TXT files (which the average user probably isn't familiar with).

Adding a full template editor to the app preferences doesn't seem right to me either. It should probably get its own space. Also, users might want to switch between multiple templates (see [here](https://help.dayoneapp.com/en/articles/2924432-templates) how Day One implemented this). So this would require significant changes to the app's UI.
