### ISSUE TITLE
Can't unlock diary after update

### ISSUE THREAD

**Issue by alexriabtsev** [samuelmeuli/mini-diary#62]
<img width="492" alt="image" src="https://user-images.githubusercontent.com/8425396/75437628-338f0e80-595f-11ea-9b94-a3f04eedbcda.png">
Looks like something went wrong after update to 3.0.0
How it could be fixed without loosing my diary?

**Comment by alexriabtsev** [comment]
Myabe the reason is that you use sha512 in hashPassword.ts and AES-192-cbc in fileAccess.ts?

**Comment by alexriabtsev** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/8425396/75438887-75b94f80-5961-11ea-9931-5b870ded3d48.png">
Looks like the file was ovewritten for some reason :( argh!

**Comment by samuelmeuli** [comment]
That's odd. The update didn't change anything about the core logic. I tested the upgrade on all platforms and it worked smoothly for me.

You can restore one of the daily backups, instructions are [here](https://github.com/samuelmeuli/mini-diary/issues/19#issuecomment-517906867). Please let me know if this works :)

**Comment by samuelmeuli** [comment]
Have you unlocked the diary with v3 before seeing this error? Or did it appear right away?

**Comment by alexriabtsev** [comment]
> That's odd. The update didn't change anything about the core logic. I tested the upgrade on all platforms and it worked smoothly for me.
> 
> You can restore one of the daily backups, instructions are [here](https://github.com/samuelmeuli/mini-diary/issues/19#issuecomment-517906867). Please let me know if this works :)

I'll try to restore later tonight.

**Comment by alexriabtsev** [comment]
> Have you unlocked the diary with v3 before seeing this error? Or did it appear right away?

It happened right away. I wasn't able to open mini-diary after upgrade.

**Comment by alexriabtsev** [comment]
OK, @samuelmeuli I'm still with mini-diary :) (yeah, I was angry so I started to look for an alternative...).
Backups restored (btw, they are in ˜/Library/Application Support/Mini Diary/backups/ but not the directory you mentioned in instructions above). I was able to open restored file and all the records are in place.
Still can't figure out why it happened. 

Could we have an easy versions upgrade through Homebrew/Cask?

**Comment by samuelmeuli** [comment]
I could add a formula, but I don't really see the benefit. Updates wouldn't happen via Cask anyway, it would still be done with the auto-updater (see [the Cask docs](https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md#updatingupgrading-casks)).

As an alternative, it looks like Electron [v8.0.2](https://github.com/electron/electron/releases/tag/v8.0.2) makes it possible to submit apps to the App Store again. I'm hoping to get Mini Diary back into the store in the future :)

**Comment by alexriabtsev** [comment]
nope, there is _brew cask upgrade <name>_
I'm using and updating JOSM this way ;)

**Comment by samuelmeuli** [comment]
> Many applications update themselves, so their Casks are ignored by brew cask outdated and brew cask upgrade.

**Comment by alexriabtsev** [comment]
>  Many applications update themselves, so their Casks are ignored by brew cask outdated and brew cask upgrade.

I guess there is no way to make auto-update for mini-diary at the moment so _brew cask upgrade_ should be a vialble solution?

**Comment by samuelmeuli** [comment]
What do you mean? Auto-updating is the current behavior.

Allowing Homebrew to handle the updating would require a separate build with the auto-updater excluded. I'm afraid this would complicate the build process too much.

**Comment by alexriabtsev** [comment]
> What do you mean? Auto-updating is the current behavior.
> 
> Allowing Homebrew to handle the updating would require a separate build with the auto-updater excluded. I'm afraid this would complicate the build process too much.

hm, strange it never auto-updated and I had to update it manually

**Comment by samuelmeuli** [comment]
What version were you on before?

**Comment by alexriabtsev** [comment]
> What version were you on before?

latest, 2.5.6 I guess

**Comment by samuelmeuli** [comment]
Maybe the app wasn't open long enough for the update to finish downloading? The update prompt only appears after it's done.

Otherwise, that would indicate a bug in [`electron-updater`](https://www.npmjs.com/package/electron-updater).

**Comment by alexriabtsev** [comment]
> Maybe the app wasn't open long enough for the update to finish downloading? The update prompt only appears after it's done.
> 
> Otherwise, that would indicate a bug in [`electron-updater`](https://www.npmjs.com/package/electron-updater).

I'm using mini-diary as journaling app so it's open as long as my laptop is on 😉
