### ISSUE TITLE
Inaccurate word count for Cyrillic script

### ISSUE THREAD

**Issue by alexriabtsev** [samuelmeuli/mini-diary#63]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/8425396/75757435-0796d300-5d3b-11ea-9f89-1398136c4f20.png">
I'm writing my morning pages but mini-diary says that I wrote only 2 words. That's frustrating 😞

**Comment by samuelmeuli** [comment]
The counting is handled by the [word-count](https://www.npmjs.com/package/word-count) library, so that's where this needs to be fixed. Please open an issue/PR in their repository instead :)

**Comment by pongo** [comment]
@samuelmeuli last release was 4 years ago. it seems word-count is abandoned. may be you fork it or use another library?

**Comment by alexriabtsev** [comment]
https://codepen.io/ericnjanga/pen/geRVMq

**Comment by samuelmeuli** [comment]
Yes, let's use a fork for now. I also reached out to the maintainer. I still hope my PRs are merged so we can use the library from NPM again.
