### ISSUE TITLE
Punctuation marks aligned incorrectly for Chinese on Windows

### ISSUE THREAD

**Issue by leeoea** [samuelmeuli/mini-diary#64]
<img width="187" alt="WeChat Screenshot_20200306132638" src="https://user-images.githubusercontent.com/43531411/76055291-28b32a00-5fae-11ea-9456-9bb3e446f22c.png">

**Comment by leeoea** [comment]
The comma and period specifically.

**Comment by samuelmeuli** [comment]
Could you please provide some more information? Where in the app is this? What's the expected output? Is this Traditional or Simplified Chinese?

**Comment by leeoea** [comment]
![image](https://user-images.githubusercontent.com/43531411/76139341-ccbdd380-6089-11ea-9892-e15c5bb83bc9.png)
This is the right version:
这是一个问题，这是一个问题。
And this bug is about  comma and period in Simplified Chinese. Thanks.

**Comment by samuelmeuli** [comment]
It's working for me:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/22477950/76139709-89f9fc80-6085-11ea-9dfc-ebe7390668fd.png">

What operating system are you using? What system language? Do you get the same issue if you're entering text in the editor on [this site](https://draftjs.org/) using Chrome?

**Comment by leeoea** [comment]
I can text normally on that site. I think the reason is that my system language is English. I found a path "mini-diary\locales". Can I do something so that I can use “zh-CN.pak” which I think is right for me.  I'm in windows 10. And I don't have this problem on last version of mini-diary. And I think it is wonderful if I could select font. Thanks~~~

**Comment by samuelmeuli** [comment]
Does the problem still occur if you change your system language to Chinese?

**Comment by leeoea** [comment]
No, it functions normally. But I want to use English as system language, so may be I should find a way to solve it. Thank you very much!

**Comment by samuelmeuli** [comment]
Just tested this myself. The problem is Windows-specific; the text displays as expected on macOS and Ubuntu.

Furthermore, the problem isn't Draft.js-specific. It also applies to the search input.

**Comment by samuelmeuli** [comment]
Seems like the alignment on Windows is correct for Traditional Chinese, but not Simplified Chinese:

![1*DtVIIeWgKPokUywK1ecxZg](https://user-images.githubusercontent.com/22477950/77432361-3fdf7d80-6dde-11ea-8c00-649c6e942739.png)

_Source: https://medium.com/@bobtung/best-practice-in-chinese-layout-f933aff1728f_

In that case, I'd say the app's behavior isn't wrong if the system language is English.

**Comment by leeoea** [comment]
Ok. Maybe I can find a way to change the font inside the app other than using the system's default font. Thanks.
