### ISSUE TITLE
What type of encryption is used?

### ISSUE THREAD

**Issue by JasonMorris1** [samuelmeuli/mini-diary#65]
What type of encryption is used? Thanks.

**Comment by samuelmeuli** [comment]
Mini Diary uses `aes-192-cbc`:

https://github.com/samuelmeuli/mini-diary/blob/7b7de97327d0cfd798511e051a55ce92b90ef3ed/src/renderer/files/fileAccess.ts#L40-L48

A hashed version of the password is used for the encryption/decryption.
