### ISSUE TITLE
No panel icon for AppImage

### ISSUE THREAD

**Issue by s3rvant** [samuelmeuli/mini-diary#71]
Ubuntu 19.10
Set AppImage to executable and double click
App launches and works as expected however panel does not have an icon
![Screenshot from 2020-04-06 09-38-47](https://user-images.githubusercontent.com/39740665/78564473-79ef4d00-77ea-11ea-8c64-97622a4f75e2.png)

**Comment by samuelmeuli** [comment]
This will need to be fixed in `electron-builder`, see https://github.com/electron-userland/electron-builder/issues/4186.
