### ISSUE TITLE
iOS/Android apps

### ISSUE THREAD

**Issue by kd2flz** [samuelmeuli/mini-diary#72]
This app is fantastic! It would be awesome if it were possible to run it on Android. Using another piece of software to sync the diary file around you would end up with a fully cross-platform app. I don't know enough about Electron to know how difficult this would be - no worries if it is prohibitively difficult.

**Comment by samuelmeuli** [comment]
Thanks for the feedback!

Currently, I unfortunately don't have the time to build and maintain mobile apps for Mini Diary. The diary's encryption method is public though, so anybody could build their own 😊

**Comment by b4allb4u** [comment]
Yes, you are correct @kd2flz . all the time, it's not possible to carry a laptop. It would be great if it is possible to run it on Android. 

once again thanks a  lot @samuelmeuli , I really enjoyed a lot with your application.
