### ISSUE TITLE
"Next month" button causes navigation to current month

### ISSUE THREAD

**Issue by jrmillerUSA** [samuelmeuli/mini-diary#73]
It looks like there's a regression with navigating the calendar.  I only have a single imported journal entry (from jrnl), and using the arrows to navigate the calendar months results in skipping of some months.   I also noticed that clicking on specific dates also flips the month (not shown below but I can screen cap that if requested).

![calendar_bug](https://user-images.githubusercontent.com/15348331/78930777-84634e00-7a59-11ea-94c8-ae8eb1c18a9d.gif)

**Comment by samuelmeuli** [comment]
You're right, I introduced a bug in 3f7ffba which breaks the function responsible for selecting the next month. This should be fixed now.

> I also noticed that clicking on specific dates also flips the month

Could you please provide an example for this?

**Comment by jrmillerUSA** [comment]
> > I also noticed that clicking on specific dates also flips the month
> 
> Could you please provide an example for this?

![calendar_bug_day_select](https://user-images.githubusercontent.com/15348331/78937155-d1005680-7a64-11ea-8360-7cb5099177e1.gif)

**Comment by samuelmeuli** [comment]
I've just released v3.1.1, which should fix these issues.

**Comment by jrmillerUSA** [comment]
Looks good on my end.  Thanks!
