### ISSUE TITLE
System language override

### ISSUE THREAD

**Issue by Z0ink5** [samuelmeuli/mini-diary#88]
Is there a way to add an _override_ to what language you use?

I wrote the Norwegian translation but I'm guessing my language either identifies as "**nb_NO**" or "**nn_NO**" (two variations of Norwegian language). I made a pull request for simply "**NO**" as that's the language in general.

Would maybe an easy workaround for this be to let us **choose language** - or "**auto**" in preferences?

**Comment by samuelmeuli** [comment]
I think that's a feature I'd prefer not to have. System language detection should be sufficient. I also haven't found any apps on my Mac that have such a feature.

**Comment by samuelmeuli** [comment]
I've created a new issue for the bug related to Norwegian language detection: #90

**Comment by samuelmeuli** [comment]
Just found out that app-specific language overrides are supported by macOS itself: `System Preferences` → `Language & Region` → `Apps`.

![image](https://user-images.githubusercontent.com/22477950/82895278-41e7c900-9f54-11ea-9953-05a8683b654a.png)
