### ISSUE TITLE
ipad version

### ISSUE THREAD

**Issue by ramin4356** [samuelmeuli/mini-diary#89]
Hi there,

Great app & I use it very frequently. The best thing of minidiary is the minimal design & password protection, makes it so easy for daily usage.

It'd have been great if we can have an ipad version.
Also, very optionally, profile for multi-users as ipad doesn't provide one.

Thanks
Ramin

**Comment by samuelmeuli** [comment]
Thanks, @ramin4356! I'm afraid I don't have the time to develop an iOS version (see #72).
