### ISSUE TITLE
Norwegian language not detected

### ISSUE THREAD

**Issue by samuelmeuli** [samuelmeuli/mini-diary#90]
Chromium supports three Norwegian locales:

Language Code | Language Name
-- | --
nb | Norwegian (Bokmal)
nn | Norwegian (Nynorsk)
no | Norwegian

Source: https://www.electronjs.org/docs/api/locales

@JeeEeEyeAre Does it make sense to use your translations for all three locales as long as there aren't different translations for the different variants?

**Comment by Z0ink5** [comment]
Hi!

**Norwegian (Bokmal)** and **Norwegian** is the same language (written and spoken).

_Nynorsk_ is a variation of the language and not entirely the same. 

Therefore we can use:
**nb
no**
